apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-inference
  labels:
    app: llm-inference
spec:
  replicas: 1   #run 1 pod
  selector:
    matchLabels:
      app: llm-inference
  template:

    metadata:
      labels:
        app: llm-inference
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4 #nvidia-l4
      containers:
        - name: llm-container
          image: ${IMAGE_URI}
          imagePullPolicy: Always

          env:
          - name: LD_LIBRARY_PATH
            value: "/usr/local/nvidia/lib64"
          
          - name: MODEL_NAME
            value: ${MODEL_NAME}

          ports:
            - name: http 
              containerPort: 8000
          
          resources:
            requests:
              cpu: "8"
              memory: "32Gi"
              nvidia.com/gpu: "1"

            limits:
              cpu: "8"
              memory: "32Gi"
              nvidia.com/gpu: "1"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 12

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 180
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 5