apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: llm-monitor
spec:
  selector:
    matchLabels:
      app: llm-inference

  endpoints:
  - port: 8000
    path: /metrics
    interval: 15s